name: Snyk Security

on:
  push:
    branches: ["master" ]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

env:
    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew
      - name: Set up Snyk CLI to check for security issues
        # Snyk can be used to break the build when it detects security issues.
        # In this case we want to upload the SAST issues to GitHub Code Scanning
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
        
      - name: run Snyk Open Source Test
        run: snyk test
        continue-on-error: true

      - name: run Snyk Code Test
        run: snyk code test
        continue-on-error: true
